(()=>{
const SKINS=['#f2d2bd','#ddb092','#bc8568','#936049','#704635','#4b3028'];
const HAIRS=['#171412','#3a261e','#704b32','#ad8255','#d7c6a5','#c9c7c5','#713039','#293750'];
const CLOTHES=['#354657','#5b4431','#3f5747','#673f42','#4d4167','#766c59'];
function defaultsFor(c={}){return{age:'adult',gender:c.sex==='여성'?'female':c.sex==='남성'?'male':'neutral',skin:SKINS[1],hair:HAIRS[0],clothes:CLOTHES[0],face:'oval',eyes:'brown',hairStyle:'none',outfit:'none'}}
function ensure(){if(typeof state==='undefined'||!state||typeof save!=='function')return false;state.character??={created:false};const old=state.character.avatar||{};const clean=defaultsFor(state.character);for(const k of Object.keys(clean))if(old[k]!==undefined)clean[k]=old[k];state.character.avatar=clean;save();return true}
function render(c,size){return typeof window.packedAvatar==='function'?window.packedAvatar(c,size):''}
function preview(c,a){const old=c.avatar;c.avatar=a;const el=document.querySelector('#avatarPreview');if(el)el.innerHTML=render(c,300);c.avatar=old}
function avatarEditor(){const c=state.character||{},a={...defaultsFor(c),...(c.avatar||{})};open(`<h2>✦ 픽셀 외형 커스텀</h2><div class="avatar-editor premium-editor"><div id="avatarPreview">${render({...c,avatar:a},300)}</div><p class="muted">모든 파츠는 고정 픽셀 좌표에 겹쳐집니다. 복장을 '없음'으로 두면 기본 맨몸 베이스가 표시됩니다.</p><div class="appearance-grid"><label>외형 연령<select id="avAge"><option value="child">어린</option><option value="youth">청년</option><option value="adult">성인</option><option value="middle">중년</option><option value="elder">노년</option></select></label><label>성별 표현<select id="avGender"><option value="male">남성형</option><option value="neutral">중성형</option><option value="female">여성형</option></select></label><label>얼굴형<select id="avFace"><option value="oval">타원형</option><option value="round">둥근형</option><option value="angular">각진형</option><option value="long">긴 얼굴</option></select></label><label>눈 색<select id="avEyes"><option value="brown">갈색</option><option value="blue">청색</option><option value="green">녹색</option><option value="gold">금색</option><option value="gray">회색</option></select></label><label>머리<select id="avHairStyle"><option value="none">민머리</option><option value="short">짧은 머리</option><option value="layered">레이어드</option><option value="bob">단발</option><option value="long">긴 머리</option><option value="wavy">웨이브</option><option value="ponytail">묶은 머리</option></select></label><label>복장<select id="avOutfit"><option value="none">없음 (맨몸)</option><option value="adventurer">모험가</option><option value="armor">갑옷</option><option value="robe">로브</option></select></label></div><label>피부색<div class="swatches">${SKINS.map(x=>`<button type="button" data-skin="${x}" style="background:${x}"></button>`).join('')}</div></label><label>머리색<div class="swatches">${HAIRS.map(x=>`<button type="button" data-hair="${x}" style="background:${x}"></button>`).join('')}</div></label><label>복장색<div class="swatches">${CLOTHES.map(x=>`<button type="button" data-clothes="${x}" style="background:${x}"></button>`).join('')}</div></label><div class="actions"><button class="primary" id="avSave">저장</button></div></div>`);
const ids={avAge:'age',avGender:'gender',avFace:'face',avEyes:'eyes',avHairStyle:'hairStyle',avOutfit:'outfit'};for(const [id,k] of Object.entries(ids)){const el=document.querySelector('#'+id);el.value=a[k];el.onchange=e=>{a[k]=e.target.value;preview(c,a)}}document.querySelectorAll('[data-skin],[data-hair],[data-clothes]').forEach(b=>b.onclick=()=>{for(const k of ['skin','hair','clothes'])if(b.dataset[k])a[k]=b.dataset[k];preview(c,a)});document.querySelector('#avSave').onclick=async()=>{state.character.avatar={...a};await save();document.dispatchEvent(new CustomEvent('chronicle:statechange'));if(typeof showPlayer==='function')showPlayer()}}
window.avatarEditor=avatarEditor;window.avatarDefaults=defaultsFor;let tries=0,t=setInterval(()=>{if(ensure()||++tries>50)clearInterval(t)},100);
})();