(()=>{
const finished=q=>['완료','실패','completed','failed'].includes(String(q?.status||'').toLowerCase());
const words=s=>String(s||'').toLowerCase().split(/[^가-힣a-z0-9]+/).filter(w=>w.length>=2);
const has=(text,list)=>list.some(w=>String(text||'').toLowerCase().includes(w));
function ensure(){window.CHRONICLE_CONTENT?.ensure?.();return typeof state!=='undefined'&&!!state}
function nearby(){const ids=new Set([...(state.present||[]),...(state.party||[])].map(String));const all=[...(state.npcs||[]),...Object.values(state.contentRegistry?.npcs||{})],seen=new Set();return all.filter(n=>n?.id&&ids.has(String(n.id))&&!seen.has(String(n.id))&&seen.add(String(n.id))).slice(-6).map(n=>({id:n.id,name:n.name,role:n.role,personality:n.personality,speech:n.speech,relation:n.relation,affinity:n.affinity,trust:n.trust,emotion:n.emotion,note:n.note,important:!!n.important}))}
function location(){const id=state.locationId,registered=state.contentRegistry?.locations?.[id],mapped=window.CHRONICLE_MAP?.getLocation?.(id);return{id,name:registered?.name||mapped?.name||id,description:registered?.description||mapped?.description||'',region:registered?.region||mapped?.region||''}}
function relevantRegistry(text){const q=words(text),out={};if(!q.length)return out;for(const type of ['items','equipment','essences','skills','monsters','locations','factions','shops','lore']){const arr=Object.values(state.contentRegistry?.[type]||{}).filter(x=>{const hay=[x.name,x.description,x.region,x.note,x.summary,x.effect].filter(Boolean).join(' ').toLowerCase();return hay&&q.some(w=>hay.includes(w))}).slice(-4);if(arr.length)out[type]=arr}return out}
function relatedMemories(text){const q=words(text);if(!q.length)return[];return(state.memories||[]).filter(m=>{const hay=[m?.text,m?.summary,m?.name,m?.npc].filter(Boolean).join(' ').toLowerCase();return q.some(w=>hay.includes(w))}).slice(-4)}
function equippedEssences(){return(state.essences||[]).filter(e=>e?.equipped===true||e?.slot!=null).map(e=>({id:e.id,name:e.name,description:e.description,effect:e.effect,slot:e.slot})).slice(0,15)}
function compactEquipment(){const out={};for(const[k,v]of Object.entries(state.equipment||{}))if(v)out[k]={id:v.id,name:v.name,rarity:v.rarity,description:v.description||v.desc,effect:v.effect,stats:v.stats,specialStats:v.specialStats};return out}
function compactPlayer(text){const p={name:state.name,level:state.level,rank:state.rank,hp:state.hp,maxHp:state.maxHp,sp:state.stamina,maxSp:state.maxStamina,equipment:compactEquipment(),equippedEssences:equippedEssences()};if(has(text,['공격','전투','때린','밀치','방패','검','활','마법','힘','근력','민첩','감식','살핀','조사','탐색','설득','협박','흥정','도망','방어','스킬','정수'])){p.stats=state.stats;p.specialStats=state.specialStats}if(has(text,['정수','능력','스킬','마법']))p.essences=state.essences;if(has(text,['인벤','소지','가방','아이템','사용','먹','마시','상자','장비','정수']))p.inventory=(state.inventory||[]).slice(-12);return p}
function build(userText,opt={}){if(!ensure())return{};const text=String(userText||''),recent=Math.max(3,Math.min(8,Number(opt.recentTurns||6))),npcs=nearby(),quests=Object.values(state.contentRegistry?.quests||{}).filter(q=>!finished(q)&&words(text).some(w=>[q.name,q.summary,q.description,q.note].filter(Boolean).join(' ').toLowerCase().includes(w))).slice(-4),facts=(state.canon?.facts||[]).filter(f=>{const hay=typeof f==='string'?f:JSON.stringify(f);return words(text).some(w=>hay.toLowerCase().includes(w))}).slice(-5);const out={protocol:'chronicle-gm-context-v3',action:text,player:compactPlayer(text),world:{day:state.day,time:state.time,location:location()},scene:{recent:(state.scene||[]).slice(-recent)}};const uiEvents=(state.playerEvents||[]).slice(-4);if(uiEvents.length)out.player.recentLoadoutChanges=uiEvents;if(npcs.length)out.scene.npcs=npcs;if(quests.length)out.quests=quests;const relevant=relevantRegistry(text);if(Object.keys(relevant).length)out.relevantContent=relevant;const memories=relatedMemories(text);if(memories.length)out.memories=memories;if(facts.length)out.world.canonFacts=facts;if(has(text,['던전','층','탐험','대던전']))out.world.dungeon=state.map?.dungeon;return out}
window.CHRONICLE_CONTEXT={build,ensure};
})();