(()=>{
const STYLE='Fantasy character portrait, single character only, parchment background, painterly high-fantasy illustration, clean readable silhouette, centered bust or half-body composition, no text, no frame, no extra people.';
const $=s=>document.querySelector(s);const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function owner(kind,id){if(kind==='player'){state.character??={};return state.character}return(state.npcs||[]).find(n=>String(n.id)===String(id))||null}
function defaultLook(o,kind){const bits=[];if(kind==='player'){bits.push(state.name||'adventurer',o.raceName||o.race,o.sex,o.age?`${o.age} years old`:null,o.build,o.height?`${o.height}cm tall`:null,o.appearance)}else bits.push(o.name,o.raceName||o.race,o.sex,o.age?`${o.age} years old`:null,o.build,o.appearance,o.note);return bits.filter(Boolean).join(', ')}
function ensure(o,kind){o.portraitStudio??={};const p=o.portraitStudio;p.fixedPrompt=String(p.fixedPrompt||defaultLook(o,kind));p.stylePrompt=String(p.stylePrompt||STYLE);p.images=Array.isArray(p.images)?p.images:[];p.selectedId=p.selectedId||null;return p}
function fullPrompt(p,extra=''){return[p.stylePrompt,p.fixedPrompt,extra].filter(Boolean).join('\n')}
function target(){return String(state.api?.portraitChatUrl||localStorage.getItem('chronicle-portrait-chat-url')||'').trim()}
function renderGallery(p){if(!p.images.length)return'<div class="portrait-empty">아직 저장된 이미지가 없습니다.</div>';return`<div class="portrait-gallery">${p.images.map(x=>`<button type="button" class="portrait-card ${p.selectedId===x.id?'selected':''}" data-pick="${esc2(x.id)}"><img src="${esc2(x.src)}" alt=""><span>${p.selectedId===x.id?'현재 프로필':'프로필로 선택'}</span></button>`).join('')}</div>`}
function show(kind='player',id=null){const o=owner(kind,id);if(!o)return;const p=ensure(o,kind);open(`<div class="portrait-studio"><header><small>PORTRAIT STUDIO</small><h2>${kind==='player'?'캐릭터':'동료'} 이미지 팩</h2><p>고정 외형을 확인·수정하고 프롬프트를 복사하면 설정에 저장한 ChatGPT 대화로 바로 이동할 수 있습니다.</p></header><label><b>고정 외형</b><textarea id="portraitFixed" rows="6">${esc2(p.fixedPrompt)}</textarea></label><label><b>공통 화풍</b><textarea id="portraitStyle" rows="4">${esc2(p.stylePrompt)}</textarea></label><label><b>이번 이미지 추가 프롬프트</b><textarea id="portraitExtra" rows="3" placeholder="예: 여행복 차림, 살짝 웃는 표정"></textarea></label><div class="portrait-actions"><button id="portraitCopy" class="primary">프롬프트 복사 + ChatGPT 열기</button><button id="portraitSavePrompt">외형 설정 저장</button></div><section class="portrait-import"><h3>이미지 팩</h3><p>이미지를 불러오면 즉시 현재 프로필 사진으로 적용됩니다. 다른 이미지를 눌러 언제든 변경할 수 있습니다.</p><input id="portraitFile" type="file" accept="image/png,image/jpeg,image/webp" hidden><button id="portraitImport">이미지 불러오기</button></section><div id="portraitGallery">${renderGallery(p)}</div></div>`);const root=$('#panelContent');const savePrompt=async()=>{p.fixedPrompt=root.querySelector('#portraitFixed').value.trim();p.stylePrompt=root.querySelector('#portraitStyle').value.trim();await save()};root.querySelector('#portraitSavePrompt').onclick=async()=>{await savePrompt();alert('외형 설정을 저장했습니다.')};root.querySelector('#portraitCopy').onclick=async()=>{await savePrompt();const text=fullPrompt(p,root.querySelector('#portraitExtra').value.trim());let copied=false;try{await navigator.clipboard.writeText(text);copied=true}catch(e){prompt('아래 프롬프트를 복사하세요.',text)}const url=target();if(url){try{const u=new URL(url);if(['http:','https:'].includes(u.protocol)){window.location.href=u.href;return}}catch(e){}}if(copied)alert('프롬프트를 복사했습니다. 설정에서 이동할 ChatGPT 링크를 지정하면 복사 후 바로 이동합니다.')};const input=root.querySelector('#portraitFile');root.querySelector('#portraitImport').onclick=()=>input.click();input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader;r.onload=async()=>{const item={id:'portrait_'+Date.now().toString(36),src:String(r.result),createdAt:Date.now()};p.images.push(item);p.images=p.images.slice(-12);p.selectedId=item.id;o.portrait=item.src;await save();document.dispatchEvent(new CustomEvent('chronicle:statechange',{detail:{state}}));show(kind,id)};r.readAsDataURL(f)};root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=async()=>{const item=p.images.find(x=>x.id===b.dataset.pick);if(!item)return;p.selectedId=item.id;o.portrait=item.src;await save();document.dispatchEvent(new CustomEvent('chronicle:statechange',{detail:{state}}));show(kind,id)})}
window.CHRONICLE_PORTRAITS={show,ensure,fullPrompt,target};
})();